### ISSUE TITLE
Create /Doc directory for Sphinx based documentation

### ISSUE THREAD

**Issue by bcottman** [neptune-ml/steppy-toolkit#26]

**Comment by kamil-kaczmarek** [comment]
Hi @bcottman,

I observe your great work on both `steppy` and `steppy-toolkit`. I will check your contribution this week and discuss it with you!

Once again, thank you for your impact on the project.

Best,
Kamil

**Comment by bcottman** [comment]
Probably load doc frame work and some more code FOR STEPPY-TOOLKIT in form of pull request.
At some point steppy may need a release-candidate instead of master?
> 
> REGARDS BRUCE

**Comment by bcottman** [comment]
done as../doc created  (needs tb merged into master)
