### ISSUE TITLE
NameError: name 'SteppyToolkitError' is not defined

### ISSUE THREAD

**Issue by apyskir** [neptune-ml/steppy-toolkit#42]
https://github.com/neptune-ml/steppy-toolkit/blob/master/toolkit/xgboost_transformers/models.py#L13

You use here SteppyToolkitError, but it's not imported, because all imports failed. This raises error as in title. You should import SteppyToolkitError after `except:`

**Comment by kamil-kaczmarek** [comment]
@apyskir thx. It is not fixed. The latest version is 0.1.13
